INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Regulador de corriente', '0', 'Regulador', '0');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Bocina Multimedia sencillas', '0', 'Bocina', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('IMPRESORA INYECCION DE TINTA A COLOR', '1', 'Impresora', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Cople jack-jack RCA', '8', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Cople jack-jack-RCA doble', '3', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Cople jack-jack 6.3mm', '9', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Cople jack-jack RCA triple', '5', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Adaptador  2 jack-plug 3.5 ', '1', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Adaptador  2 jack-plug 6.3', '8', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Adaptador canon-plug 6.3', '2', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Adaptador jack 6.3 - plug 3.5', '8', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Adaptador  2 jack RCA - Plug 6.3', '5', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Punta plug 3.5mm', '13', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Canon macho', '14', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Canon hembra', '5', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Punta RCA 3.5mm', '10', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Speak out', '6', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Cople VGA', '17', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Banano doble', '15', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Pinzas mini caiman', '5', 'Conector', '2');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Punta plug 6.3mm', '25', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Aislante Tubbing', '4', 'Aislante', '4');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Convertidor a tierra ', '3', 'Conector', '0');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Conector Banano sencillo', '21', 'Conector', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Laptop HP 240 corei3', '1', 'Laptop', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Lampara Par 64 de 177 leds', '2', 'Lampara', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable Micrófono', '0', 'Cable', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable Plug - Plug 6.3mm', '0', 'Cable', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable RCA doble - plug 3.5mm', '0', 'Cable', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable VGA 1.8 mts', '0', 'Cable', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable VGA 15 mts', '0', 'Cable', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable HDMI - HDMI', '0', 'Cable', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable Banano - Plug 6.3mm', '0', 'Cable', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable RCA - RCA', '0', 'Cable', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable VGA tipo \"Y\"', '0', 'Cable', '4');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Cable Corriente', '0', 'Cable', '0');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Extensión Electrica 8mts', '0', 'Extension', '0');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Extensión Electrica 10mts', '0', 'Extension', '0');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Extensión Electrica 15mts', '0', 'Extension', '0');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Extensión Electrica 30mts', '0', 'Extension', '0');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Extensión Multicontacto ', '0', 'Extension', '0');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Micrófono Alambrico', '0', 'Microfono', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Micrófono Inalambrico', '0', 'Microfono', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Micrófono De solapa', '0', 'Microfono', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Teclado Alambrico', '0', 'Teclado', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Teclado Inalambrico con mouse', '0', 'Teclado', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Mouse Alambrico', '0', 'Mouse', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Monitor 15\"', '0', 'Monitor', '3');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Consola Mezcladora de 6 canales', '2', 'Consola Mezcladora', '1');
INSERT INTO `audiovisual`.`material` (`nombre`, `cantidad`, `descripcion`, `categoria`) VALUES ('Stand Para micrófono de piso', '8', 'Stand', '1');